version: '3.8'
services:
  # Flask connects the frontend with the backend so that the REST-Calls reponds
  # redirect port 80 to port 5000
  # volumes save (persist) data
  flask:
    image: flask-server:latest
    restart: always
    networks:
      - example-network
    ports:
      - 5000:80
    volumes:
      - .:/code

networks:
  example-network: